name: Build

# Controls when the workflow will run
on: 
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build the solution
        run: dotnet build -c Release
             
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoReset
          path: /home/runner/work/MarkdownImageAPI/MarkdownImageAPI/bin/MarkdownImageAPI/net8.0/MarkdownImageAPI.*
        
      - name: Prepare Artifact
        id: pa
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: 
          zip -r MarkdownImageAPI.zip /home/runner/work/MarkdownImageAPI/MarkdownImageAPI/bin/Release/net8.0/MarkdownImageAPI.*
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          prerelease: false
          tag_name: V1.0.0.0
          name: Latest-Version
          files: MarkdownImageAPI.zip
      
